// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(AppDbTransferContext))]
    partial class AppDbTransferContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Location.CountryEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<DateTime>("DateCreated")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Image")
                    .HasColumnType("text");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)");

                b.Property<string>("Slug")
                    .IsRequired()
                    .HasMaxLength(250)
                    .HasColumnType("character varying(250)");

                b.HasKey("Id");

                b.ToTable("tblCountries");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Code = "UA",
                        DateCreated = new DateTime(2025, 11, 26, 21, 52, 57, 845, DateTimeKind.Utc).AddTicks(1501),
                        Image = "https://flagcdn.com/w320/ua.png",
                        IsDeleted = false,
                        Name = "Україна",
                        Slug = "ukraine"
                    },
                    new
                    {
                        Id = 2,
                        Code = "PL",
                        DateCreated = new DateTime(2025, 11, 26, 21, 52, 57, 848, DateTimeKind.Utc).AddTicks(6548),
                        Image = "https://flagcdn.com/w320/pl.png",
                        IsDeleted = false,
                        Name = "Польща",
                        Slug = "poland"
                    },
                    new
                    {
                        Id = 3,
                        Code = "DE",
                        DateCreated = new DateTime(2025, 11, 26, 21, 52, 57, 848, DateTimeKind.Utc).AddTicks(6594),
                        Image = "https://flagcdn.com/w320/de.png",
                        IsDeleted = false,
                        Name = "Німеччина",
                        Slug = "germany"
                    },
                    new
                    {
                        Id = 4,
                        Code = "CZ",
                        DateCreated = new DateTime(2025, 11, 26, 21, 52, 57, 848, DateTimeKind.Utc).AddTicks(6600),
                        Image = "https://flagcdn.com/w320/cz.png",
                        IsDeleted = false,
                        Name = "Чехія",
                        Slug = "czech-republic"
                    });
            });
        }
    }
}